# Local logging setings
logging_level: 'DEBUG'
logging_dir: 'logs'

# Neptune settings
log_to_neptune: False
neptune_username: 'pchaberski'
neptune_project: 'image-embeddings'
neptune_api_token: '<api_token>'

# Data settings
data_path: '/Users/pchaberski/data/kaggle_hm/samples/smpl_1000_20220328223037'

# Inference settings
infer_data_path: '/Users/pchaberski/data/kaggle_hm/single_folder'
infer_model_path: '/Users/pchaberski/projects/image-embeddings/output/model20220412022920'

# Output settings
output_path: 'output'

# Preprocessing settings
center: False
center_params:
  mean: [0.7662, 0.7482, 0.7468]
  std: [0.2005, 0.2172, 0.2129]

# Optimizer settings
optimizer: 'Adam'  # any valid optimizer from 'torch.optim'
optimizer_params:  # optimizer parameters to be passed as '**dict'
  lr: 0.001
lr_scheduler: MultiStepLR  # valid lr_scheduler from 'torch.optim' or None
lr_scheduler_params:  # scheduler parameters to be passed as '**dict'
  gamma: 0.1
  milestones: [20, 30]

# Training settings
embedding_size: 32
encoder: 'EncoderLinearBase'
decoder: 'DecoderLinearBase'
num_epochs: 1
batch_size: 8
num_gpus: 0
num_workers: 0  # 0 if num_gpus==0
