# Local logging setings
logging_level: 'DEBUG'
logging_dir: 'logs'

# Neptune settings
log_to_neptune: False
neptune_username: 'pchaberski'
neptune_project: 'image-embeddings'
neptune_api_token: '<api_token>'

# Data settings
data_path: '/Users/pchaberski/data/kaggle_hm/samples/smpl_1000_20220328223037'

# Preprocessing settings
image_size: [224, 224]
center: False
center_params:
  mean: [0.7662, 0.7482, 0.7468]
  std: [0.2005, 0.2172, 0.2129]

# Optimizer settings
optimizer: 'Adam'  # any valid optimizer from 'torch.optim'
optimizer_params:
  lr: 0.001

# Training settings
embedding_size: 32
encoder: 'EncoderBase'
decoder: 'DecoderBase'
num_epochs: 1
batch_size: 8
num_gpus: 0
num_workers: 0  # 0 if num_gpus==0
