# Local logging setings
logging_level: 'DEBUG'
logging_dir: 'logs'

# Neptune settings
log_to_neptune: False
neptune_username: 'pchaberski'
neptune_project: 'image-embeddings'
neptune_api_token: '<api_token>'

# Data settings
data_path: '/Users/pchaberski/data/kaggle_hm/samples/smpl_1000_20220328223037'

# Preprocessing settings
image_size: [224, 224]
normalize: False
normalization_params:
  mean: [0.7662, 0.7482, 0.7468]
  std: [0.2005, 0.2172, 0.2129]

# Training settings
batch_size: 32
